name = "sistema-inscripciones"
main = "src/index.ts"
compatibility_date = "2024-04-16"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "inscripciones_db"
database_id = "7ffed04c-fea2-47dd-a195-50124927e104"

[vars]
# El password de administrador (se puede sobrescribir en el dashboard de Cloudflare para mayor seguridad)
ADMIN_PASSWORD = "admin"
FRONTEND_URL = "https://la-cecilia-inscripciones.pages.dev" # URL de producción en Pages
